"""Multi-net / multi-layer routing functional tests using sample_board.

Test board: sample_board.kicad_pcb (generated by generate_sample_board.py)
- K nets, each net k has:
    pads (k, 0) on F.Cu <-> (0, k) on B.Cu
    tracks (k, 0)->(k, k) on F.Cu, (k, k)->(0, k) on B.Cu
    a via at (k, k) F.Cu<->B.Cu
- a polygon obstacle zone on F.Cu: y >= x+5
- trace_width=0.2, via=0.2/0.1, clearance=0.3

Coverage:
  - initial board state (track count, layers, nets, coordinates, width)
  - track deletion (by index, by coordinate)
  - reroute after deletion (F.Cu / B.Cu / multi-net)
  - behavior per routing mode (walkaround, shove, mark_obstacles)
  - save / reload consistency
"""

import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
BUILD_DIR = PROJECT_ROOT / "build_rl"
RL_MODULE_DIR = BUILD_DIR / "pcbnew" / "python" / "rl"
BOARD_PATH = PROJECT_ROOT / "tests" / "fixtures" / "sample_board.kicad_pcb"
OUTPUT_DIR = PROJECT_ROOT / "var" / "tests" / "output"

LAYER_FCU = 0
LAYER_BCU = 2
TRACE_WIDTH = 0.2

sys.path.insert(0, str(RL_MODULE_DIR))


def _import_krl():
    try:
        import kicad_rl_router as krl
        return krl
    except ImportError:
        pytest.skip(f"kicad_rl_router module not found: {RL_MODULE_DIR}")


@pytest.fixture(autouse=True)
def _ensure_output_dir() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


@pytest.fixture
def board_path() -> str:
    if not BOARD_PATH.exists():
        pytest.skip(f"test board not found: {BOARD_PATH}")
    return str(BOARD_PATH)


@pytest.fixture
def krl():
    return _import_krl()


@pytest.fixture
def router(board_path: str, krl):
    return krl.RLRouter(board_path)


def _detect_k(router) -> int:
    """Infers K (the net count) from the board."""
    return router.get_track_count() // 2


def _tracks_for_net(router, net_name: str) -> list:
    return [t for t in router.get_tracks() if t.net_name == net_name]


def _delete_tracks_for_net(router, net_name: str) -> int:
    """Deletes every track of the given net; returns the number deleted."""
    deleted = 0
    while True:
        tracks = router.get_tracks()
        idx = next((i for i, t in enumerate(tracks) if t.net_name == net_name), None)
        if idx is None:
            break
        router.delete_track_by_index(idx)
        deleted += 1
    return deleted


# ──────────────────────────────────────────────
# 1. Board load and initial state
# ──────────────────────────────────────────────
class TestBoardInitialState:
    """Checks the initial state after loading the board."""

    def test_load_success(self, router) -> None:
        assert router is not None

    def test_initial_track_count_is_even(self, router) -> None:
        """K tracks each on F.Cu and B.Cu, so the total is even."""
        assert router.get_track_count() % 2 == 0
        assert router.get_track_count() > 0

    def test_tracks_exist_on_two_layers(self, router) -> None:
        """Tracks are distributed across F.Cu(0) and B.Cu(2)."""
        layers = {t.layer for t in router.get_tracks()}
        assert LAYER_FCU in layers
        assert LAYER_BCU in layers
        assert len(layers) == 2

    def test_net_count_equals_k(self, router) -> None:
        """Unique net count across tracks equals K."""
        k = _detect_k(router)
        nets = {t.net_name for t in router.get_tracks()}
        assert len(nets) == k

    def test_each_net_has_two_tracks(self, router) -> None:
        """Each net has 1 F.Cu + 1 B.Cu track = 2 tracks."""
        k = _detect_k(router)
        for i in range(1, k + 1):
            net_tracks = _tracks_for_net(router, f"NET{i}")
            assert len(net_tracks) == 2, f"NET{i}: expected 2 tracks, got {len(net_tracks)}"

    def test_fcu_segments_are_vertical(self, router) -> None:
        """F.Cu tracks are vertical (x fixed, y varies)."""
        fcu = [t for t in router.get_tracks() if t.layer == LAYER_FCU]
        for t in fcu:
            assert t.x1_mm == pytest.approx(t.x2_mm, abs=0.01), (
                f"F.Cu track not vertical: ({t.x1_mm},{t.y1_mm})->({t.x2_mm},{t.y2_mm})"
            )

    def test_bcu_segments_are_horizontal(self, router) -> None:
        """B.Cu tracks are horizontal (y fixed, x varies)."""
        bcu = [t for t in router.get_tracks() if t.layer == LAYER_BCU]
        for t in bcu:
            assert t.y1_mm == pytest.approx(t.y2_mm, abs=0.01), (
                f"B.Cu track not horizontal: ({t.x1_mm},{t.y1_mm})->({t.x2_mm},{t.y2_mm})"
            )

    def test_track_width(self, router) -> None:
        """Every track's width is 0.2mm."""
        for t in router.get_tracks():
            assert t.width_mm == pytest.approx(TRACE_WIDTH, abs=0.01)

    def test_fcu_track_coordinates(self, router) -> None:
        """F.Cu net k track: (k, 0) -> (k, k)."""
        fcu = [t for t in router.get_tracks() if t.layer == LAYER_FCU]
        for t in fcu:
            k = int(t.net_name.replace("NET", ""))
            assert t.x1_mm == pytest.approx(k, abs=0.01)
            assert t.y1_mm == pytest.approx(0, abs=0.01)
            assert t.x2_mm == pytest.approx(k, abs=0.01)
            assert t.y2_mm == pytest.approx(k, abs=0.01)

    def test_bcu_track_coordinates(self, router) -> None:
        """B.Cu net k track: (k, k) -> (0, k)."""
        bcu = [t for t in router.get_tracks() if t.layer == LAYER_BCU]
        for t in bcu:
            k = int(t.net_name.replace("NET", ""))
            assert t.x1_mm == pytest.approx(k, abs=0.01)
            assert t.y1_mm == pytest.approx(k, abs=0.01)
            assert t.x2_mm == pytest.approx(0, abs=0.01)
            assert t.y2_mm == pytest.approx(k, abs=0.01)


# ──────────────────────────────────────────────
# 2. Track deletion
# ──────────────────────────────────────────────
class TestTrackDeletion:
    """Checks track deletion."""

    def test_delete_by_index(self, router) -> None:
        before = router.get_track_count()
        assert router.delete_track_by_index(0) is True
        assert router.get_track_count() == before - 1

    def test_delete_by_near(self, router) -> None:
        """Coordinate-based deletion (NET1 F.Cu track)."""
        before = router.get_track_count()
        t = next(
            t for t in router.get_tracks()
            if {(round(t.x1_mm, 3), round(t.y1_mm, 3)),
                (round(t.x2_mm, 3), round(t.y2_mm, 3))} == {(1.0, 0.0), (1.0, 1.0)}
        )
        result = router.delete_track_near(1.0, 0.0, 1.0, 1.0, t.layer, t.net_code, 0.1)
        assert result is True
        assert router.get_track_count() == before - 1

    def test_delete_all_tracks_of_one_net(self, router) -> None:
        """Deletes every track of one net."""
        before = router.get_track_count()
        deleted = _delete_tracks_for_net(router, "NET1")
        assert deleted == 2
        assert router.get_track_count() == before - 2
        assert len(_tracks_for_net(router, "NET1")) == 0

    def test_other_nets_unaffected_after_deletion(self, router) -> None:
        """Other nets are unchanged after deleting one net."""
        _delete_tracks_for_net(router, "NET1")
        net2_tracks = _tracks_for_net(router, "NET2")
        assert len(net2_tracks) == 2


# ──────────────────────────────────────────────
# 3. Reroute after deletion (F.Cu)
# ──────────────────────────────────────────────
class TestRerouteFCu:
    """Reroute after deleting the F.Cu segment."""

    def _delete_fcu_track(self, router, net_idx: int) -> None:
        """Deletes only net_idx's F.Cu track."""
        while True:
            tracks = router.get_tracks()
            idx = next(
                (
                    i
                    for i, t in enumerate(tracks)
                    if t.net_name == f"NET{net_idx}" and t.layer == LAYER_FCU
                ),
                None,
            )
            if idx is None:
                break
            router.delete_track_by_index(idx)

    def test_reroute_fcu_direct(self, router, krl) -> None:
        """Reroutes pad->via directly after deleting NET1's F.Cu track."""
        self._delete_fcu_track(router, 1)
        before = router.get_track_count()

        router.set_routing_mode(krl.MODE_WALKAROUND)
        started = router.start_route(1.0, 0.0, LAYER_FCU)
        assert started is True

        router.move(1.0, 0.5)
        success = router.fix_route(1.0, 1.0, force_finish=True)
        assert success is True
        assert router.is_routing() is False
        assert router.get_track_count() > before

    def test_reroute_fcu_with_waypoint(self, router, krl) -> None:
        """Reroutes via a waypoint after deleting NET2's F.Cu track."""
        self._delete_fcu_track(router, 2)
        before = router.get_track_count()

        router.set_routing_mode(krl.MODE_WALKAROUND)
        router.start_route(2.0, 0.0, LAYER_FCU)
        router.move(2.0, 1.0)
        router.fix_route(2.0, 1.0, force_finish=False)
        assert router.is_routing() is True

        success = router.fix_route(2.0, 2.0, force_finish=True)
        assert success is True
        assert router.get_track_count() > before


# ──────────────────────────────────────────────
# 4. Reroute after deletion (B.Cu)
# ──────────────────────────────────────────────
class TestRerouteBCu:
    """Reroute after deleting the B.Cu segment."""

    def _delete_bcu_track(self, router, net_idx: int) -> None:
        while True:
            tracks = router.get_tracks()
            idx = next(
                (
                    i
                    for i, t in enumerate(tracks)
                    if t.net_name == f"NET{net_idx}" and t.layer == LAYER_BCU
                ),
                None,
            )
            if idx is None:
                break
            router.delete_track_by_index(idx)

    def test_reroute_bcu_direct(self, router, krl) -> None:
        """Reroutes via->pad directly after deleting NET1's B.Cu track."""
        self._delete_bcu_track(router, 1)
        before = router.get_track_count()

        router.set_routing_mode(krl.MODE_WALKAROUND)
        started = router.start_route(1.0, 1.0, LAYER_BCU)
        assert started is True

        router.move(0.5, 1.0)
        success = router.fix_route(0.0, 1.0, force_finish=True)
        assert success is True
        assert router.get_track_count() > before

    def test_reroute_bcu_with_waypoint(self, router, krl) -> None:
        """Reroutes via a waypoint after deleting NET3's B.Cu track."""
        self._delete_bcu_track(router, 3)
        before = router.get_track_count()

        router.set_routing_mode(krl.MODE_WALKAROUND)
        router.start_route(3.0, 3.0, LAYER_BCU)
        router.move(1.5, 3.0)
        router.fix_route(1.5, 3.0, force_finish=False)
        assert router.is_routing() is True

        success = router.fix_route(0.0, 3.0, force_finish=True)
        assert success is True
        assert router.get_track_count() > before


# ──────────────────────────────────────────────
# 5. Behavior per routing mode
# ──────────────────────────────────────────────
class TestRoutingModes:
    """Checks reroute behavior for each routing mode."""

    @pytest.mark.parametrize(
        "mode_name,mode_attr",
        [
            ("walkaround", "MODE_WALKAROUND"),
            ("shove", "MODE_SHOVE"),
            ("mark_obstacles", "MODE_MARK_OBSTACLES"),
        ],
    )
    def test_reroute_with_mode(
        self, board_path: str, krl, mode_name: str, mode_attr: str
    ) -> None:
        """Reroute succeeds in each mode after deleting NET1's F.Cu track."""
        router = krl.RLRouter(board_path)
        _delete_tracks_for_net(router, "NET1")

        mode = getattr(krl, mode_attr)
        router.set_routing_mode(mode)

        started = router.start_route(1.0, 0.0, LAYER_FCU)
        assert started, f"start_route failed (mode={mode_name})"

        router.move(1.0, 0.5)
        success = router.fix_route(1.0, 1.0, force_finish=True)
        assert success, f"fix_route failed (mode={mode_name})"
        assert router.get_track_count() > 0


# ──────────────────────────────────────────────
# 6. Sequential reroute after deleting multiple nets
# ──────────────────────────────────────────────
class TestMultiNetReroute:
    """Checks sequential reroute after deleting multiple nets."""

    def test_reroute_three_nets_sequentially(self, board_path: str, krl) -> None:
        """Reroutes NET1, NET2, NET3 in order after deleting their F.Cu tracks."""
        router = krl.RLRouter(board_path)
        target_nets = [1, 2, 3]

        for k in target_nets:
            tracks = router.get_tracks()
            idx = next(
                (
                    i
                    for i, t in enumerate(tracks)
                    if t.net_name == f"NET{k}" and t.layer == LAYER_FCU
                ),
                None,
            )
            if idx is not None:
                router.delete_track_by_index(idx)

        for k in target_nets:
            router.set_routing_mode(krl.MODE_WALKAROUND)
            started = router.start_route(float(k), 0.0, LAYER_FCU)
            assert started, f"NET{k} start_route failed"

            router.move(float(k), float(k) * 0.5)
            success = router.fix_route(float(k), float(k), force_finish=True)
            assert success, f"NET{k} fix_route failed"

    def test_cancel_does_not_affect_other_nets(self, board_path: str, krl) -> None:
        """Canceling one net's routing does not affect other nets."""
        router = krl.RLRouter(board_path)
        count_before = router.get_track_count()

        _delete_tracks_for_net(router, "NET1")
        count_after_delete = router.get_track_count()

        router.set_routing_mode(krl.MODE_WALKAROUND)
        router.start_route(1.0, 0.0, LAYER_FCU)
        router.move(1.0, 0.5)
        router.cancel_route()

        assert router.get_track_count() == count_after_delete
        assert router.is_routing() is False

        net2_tracks = _tracks_for_net(router, "NET2")
        assert len(net2_tracks) == 2


# ──────────────────────────────────────────────
# 7. Save / reload consistency
# ──────────────────────────────────────────────
class TestSaveReload:
    """Checks track consistency across save and reload."""

    def test_save_and_reload_preserves_tracks(self, board_path: str, krl) -> None:
        """Save then reload the original board: track count and coordinates match."""
        router = krl.RLRouter(board_path)
        output = OUTPUT_DIR / "sample_save_reload.kicad_pcb"

        router.save(str(output))

        router2 = krl.RLRouter(str(output))
        assert router2.get_track_count() == router.get_track_count()

        t1 = router.get_tracks()
        t2 = router2.get_tracks()
        for a, b in zip(t1, t2):
            assert a.x1_mm == pytest.approx(b.x1_mm, abs=0.001)
            assert a.y1_mm == pytest.approx(b.y1_mm, abs=0.001)
            assert a.net_name == b.net_name

    def test_save_after_reroute(self, board_path: str, krl) -> None:
        """Save then reload after a reroute: the changed tracks are reflected."""
        router = krl.RLRouter(board_path)
        _delete_tracks_for_net(router, "NET1")

        router.set_routing_mode(krl.MODE_WALKAROUND)
        router.start_route(1.0, 0.0, LAYER_FCU)
        router.move(1.0, 0.5)
        router.fix_route(1.0, 1.0, force_finish=True)

        count_after = router.get_track_count()
        output = OUTPUT_DIR / "sample_save_after_reroute.kicad_pcb"
        router.save(str(output))

        router2 = krl.RLRouter(str(output))
        assert router2.get_track_count() == count_after


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
